#!/bin/bash

echo "Guest - user name should be pi here or you are going to have a bad time"

sudo apt-get install apache2 openssh-server iftop psmisc

sudo chmod u+s /usr/bin/lsof

sudo setcap cap_net_raw,cap_net_admin+eip /usr/sbin/iftop

sudo cp apache2.conf /etc/apache2/

#user name specific
sudo cp inittab /etc/inittab

#user name specific
#cp profile ~/.profile
#sudo cp profile ~/.profile
#put the file in the correct place whether this script is run as root or not
#previously if the script itself ran as root the file would mistakenly go into /root
cp profile /home/pi/.profile

echo "Now it is time to install scripts in /usr/lib/cgi-bin and web stuff in /var/www/html and change the SSH port number and password"

